apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    grafana_datasource: "1"
    namespace: grafana
  {{- include "grafana.labels" . | nindent 4 }}
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
  {{ if .Values.grafana.datasources.jaeger.enabled }}      
    - access: proxy
      jsonData:
       {{ if .Values.grafana.datasources.loki.enabled }}   
        tracesToLogs:
          datasourceUid: loki
          filterBySpanID: false
          filterByTraceID: false
          mapTagNamesEnabled: false
          mappedTags:
          - key: service.name
            value: service
          spanEndTimeShift: 1h
          spanStartTimeShift: 1h
          tags:
          - job
          - instance
          - pod
          - namespace
       {{ end }}            
       {{ if .Values.grafana.datasources.prometheus.enabled }}   
        tracesToMetrics:
          datasourceUid: prom
          queries:
          - name: Sample query
            query: sum(rate(tempo_spanmetrics_latency_bucket{$__tags}[5m]))
          tags:
          - key: service.name
            value: service
          - key: job
       {{ end }}  
      name: Jaeger
      type: jaeger
      uid: jaeger-spectra
      url: {{ .Values.grafana.datasources.jaeger.endpoint }}
  {{ end }}      
  {{ if .Values.grafana.datasources.prometheus.enabled }}
    - access: proxy
      editable: true
      isDefault: true
      name: Prometheus
      uid: prom
      type: prometheus
      url: {{ .Values.grafana.datasources.prometheus.endpoint }}
      version: 1
  {{ end }}
  {{ if .Values.grafana.datasources.tempo.enabled }}  
    - access: proxy
      apiVersion: 1
      basicAuth: false
      editable: true
      isDefault: false
      name: Tempo
      orgId: 1
      type: tempo
      uid: tempo
      url: {{ .Values.grafana.datasources.tempo.endpoint }}
      version: 1
  {{ end }}     
  {{ if .Values.grafana.datasources.loki.enabled }}     
    - access: proxy
      jsonData:
        maxLines: 1000
      name: Loki
      uid: loki
      type: loki
      url: {{ .Values.grafana.datasources.loki.endpoint }}
  {{ end }}      
  grafana.ini: {{ .Values.grafana.config.grafanaIni | quote }}