apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  labels:
  {{- include "grafana.labels" . | nindent 4 }}
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana
  labels:
  {{- include "grafana.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana
  labels:
  {{- include "grafana.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'grafana'
subjects:
- kind: ServiceAccount
  name: 'grafana'
  namespace: '{{ .Release.Namespace }}'