apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
  {{- include "grafana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.grafana.grafanaSvc.type }}
  selector:
    app: grafana
  {{- include "grafana.selectorLabels" . | nindent 4 }}
  ports:
  - name: grafana-http
    port: {{ .Values.grafana.grafanaSvc.port }}
    protocol: TCP
    targetPort: {{ .Values.grafana.port }}
