name: Main Branch CI
on: 
  push:
    branches: 
      - feature/release-management
jobs:
  Build-Code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore iotedge/Distributed.Azure.IoT.Edge
    - name: Build
      run: dotnet build iotedge/Distributed.Azure.IoT.Edge --no-restore
    - name: Test
      run: dotnet test iotedge/Distributed.Azure.IoT.Edge --no-build --verbosity normal
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo main-f-${GITHUB_SHA})
    - name: echo tag
      run: echo ${{steps.vars.outputs.tag}}
      
    # - name: Build the tagged Docker image for Iot Hub Integration module.
    #   run: docker build iotedge/Distributed.Azure.IoT.Edge/. --file iotedge/Distributed.Azure.IoT.Edge/Distributed.Azure.IoT.Edge.IoTHubIntegrationModule/Dockerfile --tag suneetnangia/distributed-az-iot-edge-iothubintegrationmodule:${{steps.vars.outputs.tag}}
    # - name: Push the tagged Docker image for Iot Hub Integration module.
    #   run: docker push suneetnangia/distributed-az-iot-edge-iothubintegrationmodule:${{steps.vars.outputs.tag}}

    # - name: Build the latest Docker image for Iot Hub Integration module.
    #   run: docker build iotedge/Distributed.Azure.IoT.Edge/. --file iotedge/Distributed.Azure.IoT.Edge/Distributed.Azure.IoT.Edge.IoTHubIntegrationModule/Dockerfile --tag suneetnangia/distributed-az-iot-edge-iothubintegrationmodule:main-ci-latest
    # - name: Push the latest Docker image for Iot Hub Integration module.
    #   run: docker push suneetnangia/distributed-az-iot-edge-iothubintegrationmodule:main-ci-latest
      
    # - name: Build the tagged Docker image for Simulated Temperature Sensor module.
    #   run: docker build iotedge/Distributed.Azure.IoT.Edge/. --file iotedge/Distributed.Azure.IoT.Edge/Distributed.Azure.IoT.Edge.SimulatedTemperatureSensorModule/Dockerfile --tag suneetnangia/distributed-az-iot-edge-simulatedtemperaturesensormodule:${{steps.vars.outputs.tag}}
    # - name: Push the tagged Docker image for Simulated Temperature Sensor module.
    #   run: docker push suneetnangia/distributed-az-iot-edge-simulatedtemperaturesensormodule:${{steps.vars.outputs.tag}}

    # - name: Build the latest Docker image for Simulated Temperature Sensor module.
    #   run: docker build iotedge/Distributed.Azure.IoT.Edge/. --file iotedge/Distributed.Azure.IoT.Edge/Distributed.Azure.IoT.Edge.SimulatedTemperatureSensorModule/Dockerfile --tag suneetnangia/distributed-az-iot-edge-simulatedtemperaturesensormodule:main-ci-latest
    # - name: Push the latest Docker image for Simulated Temperature Sensor module.
    #   run: docker push suneetnangia/distributed-az-iot-edge-simulatedtemperaturesensormodule:main-ci-latest

  Release-Artifacts:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Configure Git
          run: |
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

        - name: Run chart-releaser
          uses: helm/chart-releaser-action@v1.1.0
          env:
            CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          with:
            charts_dir: deployment/helm