# Simulated Temperature Sensor module settings
simulatedTemperatureSensorFeedIntervalInMilliseconds: 1000

# Data Gateway module settings
dataGatewayModule:
  eventHubConnectionString: "replace_with_real_key_at_deploy_time"
  storageAccountName: "replace_with_storage_account_name_at_deploy_time"
  storageAccountKey: "replace_with_storage_account_key_at_deploy_time"