# Simulated Temperature Sensor module settings
simulatedTemperatureSensorFeedIntervalInMilliseconds: 1000

# Data Gateway module settings
dataGatewayModule:
  eventHubConnectionString: "replace_with_real_key_at_deploy_time"
  storageAccountName: "replace_with_storage_account_name_at_deploy_time"
  storageAccountKey: "replace_with_storage_account_key_at_deploy_time"

# Local Pub Sub module settings
localPubSubModule:
  redisUri: "redis-master.edge-core.svc.cluster.local:6379"

# OPC Publisher module settings
opcPublisherModule:
  mm: PubSub
  pubsub: local-pub-sub
  topic: telemetry

# Docker images
images:
  datagatewaymodule: Azure-Samples/distributed-az-iot-edge-datagatewaymodule:main-40c99e12a1e8db086fcc20780b2533b14fab3668
  simulatedtemperaturesensormodule: Azure-Samples/distributed-az-iot-edge-simulatedtemperaturesensormodule:main-40c99e12a1e8db086fcc20780b2533b14fab3668
  opcplcmodule: mcr.microsoft.com/iotedge/opc-plc:2.2.0
  opcpublishermodule: Azure-Samples/distributed-az-iot-edge-opcuapublisher:latest
