# Simulated Temperature Sensor module settings
simulatedTemperatureSensorFeedIntervalInMilliseconds: 1000

# Data Gateway module settings
dataGatewayModule:
  eventHubConnectionString: "replace_with_real_key_at_deploy_time"
  storageAccountName: "replace_with_storage_account_name_at_deploy_time"
  storageAccountKey: "replace_with_storage_account_key_at_deploy_time"

# Local Pub Sub module settings
localPubSubModule:
  mqttUri: "tcp://mosquitto.edge-core.svc.cluster.local:1883"

# OPC Publisher module settings
opcPublisherModule:
  mm: PubSub
  pubsub: local-pub-sub
  topic: telemetry

# Docker images
images:
  datagatewaymodule: ghcr.io/azure-samples/distributed-az-iot-edge/datagatewaymodule:main-78b133d
  simulatedtemperaturesensormodule: ghcr.io/azure-samples/distributed-az-iot-edge/simulatedtemperaturesensormodule:main-78b133d
  opcplcmodule: mcr.microsoft.com/iotedge/opc-plc:2.2.0
  opcpublishermodule: ghcr.io/azure-samples/distributed-az-iot-edge/opcuapublisher:main-78b133d
