apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: iot-edge-accelerator-release
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./deployment/helm
      # Enable this if you want to deploy only a specific chart version.
      # https://fluxcd.io/docs/guides/helmreleases/#define-a-helm-release
      # version: "0.18.0"
      sourceRef:
        kind: GitRepository        
        name: iot-edge-accelerator-repo
        namespace: flux-system
      interval: 1m  
  valuesFrom:
  - kind: Secret
    name: iothub-integration-module-secret-seed
    valuesKey: iothubIntegrationModuleDevicePrimaryKey
