# https://fluxcd.io/docs/guides/helmreleases/
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: iot-edge-accelerator-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://suneetnangia.github.io/distributed-az-edge-framework
