apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-pub-sub
spec:
  type: pubsub.mqtt3
  version: v1
  metadata:
  - name: url
    value: mqtt://localhost:1883
  - name: retain
    value: "false"
  - name: cleanSession
    value: "false"
  - name: qos
    value: "1"
  - name: consumerID
    value: "workflow-module"
