apiVersion: v1
kind: Service
metadata:
  name: dsnmasq-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: dnsmasq
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53