{{- if .Values.fluentbit.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: fluentbit-service
  namespace: {{ .Release.Namespace }}
  labels: 
    k8s-app: fluent-bit
    addonmanager.kubernetes.io/mode: Reconcile
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2020"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 2020
    protocol: TCP
    targetPort: http
  selector:
    k8s-app: fluent-bit
{{- end -}}