{{- if .Values.fluentbit.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: fluent-bit

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
  template:
    metadata:
      name: fluent-bit
      labels:
        app.kubernetes.io/name: fluent-bit
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: fluent-bit
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 10
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: fluent-bit
          image: {{ .Values.fluentbit.image }}:{{ .Values.fluentbit.tag }}
          imagePullPolicy: IfNotPresent
          args:
            - --workdir=/fluent-bit/etc
            - --config=/fluent-bit/etc/fluent-bit.conf
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/

      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
{{- end -}}