nameOverride: "mosquitto"
fullnameOverride: ""

# mosquitto image repo, tag and pull policy
image: 
  repository: eclipse-mosquitto
  tag: latest
  pullPolicy: IfNotPresent

# mosquitto default MQTT port
defaultport: 1883

# deployment replica count
replicaCount: 1

# mosquitto pod resources collection
resources:
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "500m"

# mosquitto deployment nodeSelectors{
nodeSelector: {}

# mosquitto pod tolerations
tolerations: []

# mosquitto pod affinity
affinity: {}

# mosquitto service type
service:
  type: LoadBalancer

# mosquitto persistence options for deployment
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  annotations: {}
  storageClass: managed-csi

# contents of mosquitto.conf file
mosquittoConfig: |-
  persistence true
  persistence_location /mosquitto/data/
  log_dest stdout
  allow_anonymous true
  listener 1883
  protocol mqtt