apiVersion: v1
kind: Service
metadata:
  name: mosquittocluster
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.defaultPort }}
      targetPort: {{ .Values.defaultPort }}
      name: default
      protocol: TCP
  selector:
    app: {{ include "mosquitto.name" . }}