apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-certs
data:
  ca.crt: |-
    {{- .Values.certs.ca.crt | nindent 4 }}
  server.crt: |-
    {{- .Values.certs.server.crt | nindent 4 }}
  server.key: |-
    {{- .Values.certs.server.key | nindent 4 }}
  bridgeca.crt: |-
    {{- .Values.certs.bridgeca.crt | nindent 4 }}
  bridgeclient.crt: |-
    {{- .Values.certs.bridgeclient.crt | nindent 4 }}
  bridgeclient.key: |-
    {{- .Values.certs.bridgeclient.key | nindent 4 }}
