apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.defaultport }}
      targetPort: default
      name: default
      protocol: TCP
  selector:
    app: {{ include "mosquitto.name" . }}