# System Data Gateway module/pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-gateway-module-deployment
  labels:
    app: data-gateway-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-gateway-module
  template:
    metadata:
      labels:
        app: data-gateway-module
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "data-gateway-module"
        dapr.io/app-port: "80"
        dapr.io/app-protocol: "grpc"
        dapr.io/log-as-json: "true"
        dapr.io/enable-metrics: {{ .Values.observability.enabled | quote }}
        dapr.io/metrics-port: "9090"
        {{- if .Values.observability.enabled }}
        dapr.io/config: "l4-tracingconfig"
        dapr.io/log-level: {{ .Values.observability.daprLogLevel | quote }}
        {{ end }}
    spec:
      containers:
      - name: data-gateway-module
        image: {{ .Values.images.datagatewaymodule }}
        imagePullPolicy: Always
        args: ["--receiverPubSubName", "{{ .Values.gatewayPubSubModule.name }}"]
        env:
        - name: Logging__LogLevel__Default
          value: {{ .Values.dataGatewayModule.logLevel | quote }}
        - name: Logging__LogLevel__Microsoft__AspNetCore # note this is still an open issue in .NET / for usage of periods in namespaces see https://github.com/dotnet/runtime/issues/35989
          value: {{ .Values.dataGatewayModule.logLevel | quote }}
        - name: Logging__Console__FormatterName
          value: "Json"
      restartPolicy: Always
