apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.opcPublisherModule.pubsub }}
spec:
  type: pubsub.mqtt3
  version: v1
  metadata:
  - name: url
    value: {{ .Values.localPubSubModule.mqttUri }}
  - name: retain
    value: "false"
  - name: cleanSession
    value: "false"
  - name: qos
    value: "1"
  - name: consumerID
    value: "{podName}"
  # Lock down type of access for each service.
  - name: publishingScopes
    value: "simulated-temperature-sensor-module=telemetry;opc-publisher-module=telemetry"
  - name: subscriptionScopes
    value: "simulated-temperature-sensor-module=;opc-publisher-module="
  # Lock down the topics on this pubsub component.
  - name: allowedTopics
    value: "telemetry"

scopes:
- simulated-temperature-sensor-module
- opc-publisher-module