# envoy proxy settings
envoyReverseProxy:
  httpsContainerPort: 50000
  httpsPort: 443

command:
  - /usr/local/bin/envoy

args:
  - -c
  - /etc/envoy/envoy.yaml
  - -l
  - debug

parent:
  enabled: false
  proxyIp: to_replace
  proxyHttpsPort: 443

domainRegion: northeurope

arcDomainNames:
  management_azure_com: management.azure.com
  management_core_windows_net: management.core.windows.net
  login_windows_net: login.windows.net
  mcr_microsoft_com: mcr.microsoft.com
  guestnotificationservice_azure_com: guestnotificationservice.azure.com
  login_microsoftonline_com: login.microsoftonline.com
  k8connecthelm_azureedge_net: k8connecthelm.azureedge.net
  sts_windows_net: sts.windows.net
  k8sconnectcsp_azureedge_net: k8sconnectcsp.azureedge.net
  graph_microsoft_com: graph.microsoft.com
  azurepolicyarckubernetes_azurecr_io: azurepolicyarckubernetes.azurecr.io # not documented
  graph_windows_net: graph.windows.net # from arc 'server' requirements
  manifestcdndev_azureedge_net: manifestcdndev.azureedge.net # not documented
  data_policy_core_windows_net: data.policy.core.windows.net # not documented
  #gbl_his_arc_azure_com: gbl.his.arc.azure.com # will be matched via the wildcard domains
  # dc_services_visualstudio_com: dc.services.visualstudio.com # from arc server requirements
  # aka_ms: aka.ms # from arc 'server' requirements
  # pas_windows_net: pas.windows.net # from arc 'server'requirements


arcRegionalDomains:
  region_dp_kubernetesconfg_azure_com: .dp.kubernetesconfiguration.azure.com
  region_rp_kubernetesconfg_azure_com: .rp.kubernetesconfiguration.azure.com
  region_data_mcr_microsoft_com: .data.mcr.microsoft.com
  region_login_microsoft_com: .login.microsoft.com
  region_monitoring_azure_com: .monitoring.azure.com # from other docs

arcWildcardSubDomains:
  his_arc_azure_com: "*.his.arc.azure.com"
  arc_azure_net: "*.arc.azure.net"
  guestconfiguration_azure_com: "*.guestconfiguration.azure.com"
  azwebsites: "*.azurewebsites.net" # just for testing

# Provide additional domains that you want to proxy through, pass the whole collection through Values
# customDomains:
#   domain1: www.domain1.com
