# envoy proxy settings
envoyReverseProxy:
  httpsContainerPort: 50000
  httpsPort: 443
command:
  - /usr/local/bin/envoy
args:
  - -c
  - /etc/envoy/envoy.yaml
  - -l
  - info

parent:
  enabled: false
  proxyIp: to_replace
  proxyHttpsPort: 443