apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-configmap
data:
  envoy.yaml: |-
    admin:
      address:
        socket_address: { address: 0.0.0.0, port_value: 9901 }

    static_resources:
      listeners:
      - name: https_listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 50000
        
        listener_filters:
        - name: envoy.filters.listener.tls_inspector
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
        per_connection_buffer_limit_bytes: 32768  # 32 KiB
        filter_chains:
        {{- $domainRegion := .Values.domainRegion -}}
        {{- if .Values.parent.enabled }}
        - filter_chain_match:
            server_names:
              {{- range $key, $val := .Values.arcDomainNames }}
              - {{ $val }}
              {{- end }}
              {{- range $key, $val := .Values.arcRegionalDomains }}
              - {{ $domainRegion -}} {{ $val }}
              {{- end }}
              {{- range $key, $val := .Values.customDomains }}
              - {{ $val }}
              {{- end }}
              {{- range $key, $val := .Values.arcWildcardSubDomains }}
              - {{ $val | quote }}
              {{- end }}
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: parent-passthrough
                stat_prefix: parent_passthr
        {{- else }}
        {{- range $key, $val := .Values.arcDomainNames }}
        - filter_chain_match:
            server_names:
              - {{ $val }}
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: {{ $key }}
                stat_prefix: {{ $key }}_tcp
        {{- end }}
        {{- range $key, $val := .Values.arcRegionalDomains }}
        - filter_chain_match:
            server_names:
              - {{ $domainRegion -}} {{ $val }}
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: {{ $key }}
                stat_prefix: {{ $key }}_tcp
        {{- end }}
        {{- range $key, $val := .Values.customDomains }}
        - filter_chain_match:
            server_names:
              - {{ $val }}
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: {{ $key }}
                stat_prefix: {{ $key }}_tcp
        {{- end }}
        {{- if .Values.arcWildcardSubDomains}}
        # Temporary solution for wildcard subdomains, using SNI foward proxy which is not production ready
        # Must be the last filter chain in the list to match wildcard domains that have not been matched above
        # Example gbl.his.arc.azure.com is matched above, all other *.his.arc.azure.com will be matched here
        - filter_chain_match:
            server_names:
              {{- range $key, $val := .Values.arcWildcardSubDomains }}
              - {{ $val | quote }}
              {{- end }} 
          filters:
            - name: envoy.filters.network.sni_dynamic_forward_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.sni_dynamic_forward_proxy.v3.FilterConfig
                port_value: {{ .Values.parent.proxyHttpsPort }}
                dns_cache_config:
                  name: dynamic_forward_proxy_cache_config
                  dns_lookup_family: V4_ONLY
            - name: envoy.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: forward_wildcard_tcp
                cluster: dynamic_forward_proxy_cluster
        {{- end }}
        {{- end }} 

      - name: obo_listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: {{ .Values.envoyReverseProxy.oboPort }}
        
        listener_filters:
        - name: envoy.filters.listener.tls_inspector
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
        per_connection_buffer_limit_bytes: 32768  # 32 KiB
        filter_chains:
        {{- $domainRegion := .Values.domainRegion -}}
        {{- if .Values.parent.enabled }}
        - filter_chain_match:
            server_names:
              - {{ $domainRegion -}} {{ .Values.arcOboClusterConnect.region_obo_arc_azure_com }}
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: parent-passthrough-obo
                stat_prefix: parent_passthr_obo
        {{- else }}
        
        - filter_chain_match:
            server_names:
              - {{ $domainRegion -}} {{ .Values.arcOboClusterConnect.region_obo_arc_azure_com }}
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: region-obo-arc-azure-com
                stat_prefix: obo_tcp
        {{- end }}
      
        
      clusters:
      
      {{- if .Values.parent.enabled }}
      # If child layer point to parent proxy entrypoint
      - name: parent-passthrough
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        load_assignment:
          cluster_name: parent-passthrough
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .Values.parent.proxyIp }}
                    port_value: {{ .Values.parent.proxyHttpsPort }}
                    
      - name: parent-passthrough-obo
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        load_assignment:
          cluster_name: parent-passthrough-obo
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .Values.parent.proxyIp }}
                    port_value: {{ .Values.parent.proxyOboPort }}
      {{- else }}
      # else if this is top layer point to outbound public URIs
      {{- $httpsPort := .Values.parent.proxyHttpsPort -}}
      {{- range $key, $val := .Values.arcDomainNames }}
      - name: {{ $key }}
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        load_assignment:
          cluster_name: {{ $key }}
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ $val }}
                    port_value: {{ $httpsPort }}
      {{- end }}
      {{- range $key, $val := .Values.arcRegionalDomains }}
      - name: {{ $key }}
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        load_assignment:
          cluster_name: {{ $key }}
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ $domainRegion -}} {{ $val }}
                    port_value: {{ $httpsPort }}
      {{- end }}
      {{- range $key, $val := .Values.customDomains }}
      - name: {{ $key }}
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        load_assignment:
          cluster_name: {{ $key }}
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ $val }}
                    port_value: {{ $httpsPort }}
      {{- end }}
      {{- if .Values.arcWildcardSubDomains}}
      - name: dynamic_forward_proxy_cluster
        lb_policy: CLUSTER_PROVIDED
        cluster_type:
          name: envoy.clusters.dynamic_forward_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
            dns_cache_config:
              name: dynamic_forward_proxy_cache_config
              dns_lookup_family: V4_ONLY
      
      {{- end }}

      {{- $oboPort := .Values.parent.proxyOboPort -}}
      {{- if .Values.arcOboClusterConnect }}
      - name: region-obo-arc-azure-com
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        load_assignment:
          cluster_name: region-obo-arc-azure-com
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ $domainRegion -}} {{ .Values.arcOboClusterConnect.region_obo_arc_azure_com }}
                    port_value: {{ $oboPort }}
      
      {{- end }}


      {{- end }}

    layered_runtime:
      layers:
      - name: static_layer_0
        static_layer:
          overload:
            global_downstream_max_connections: 50000