apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-configmap
data:
  envoy.yaml: |-
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address: { address: 0.0.0.0, port_value: 9901 }

    static_resources:
      listeners:
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 50000
        {{- if .Values.parent.enabled }}
        listener_filters:
        - name: "single_tls_inspector"
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
        filter_chains:
        - filter_chain_match:
            server_names:
              - management.azure.com
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: management-azure-com
                stat_prefix: mng-azure-com_passthr
        - filter_chain_match:
            server_names:
              - login.windows.net
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: login-windows-net
                stat_prefix: login-windows-net_passthr
        - filter_chain_match:
            server_names:
              - www.google.com
              - google.com
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: www-google-com
                stat_prefix: google-com_passthr
        - filter_chain_match:
            server_names:
              - mcr.microsoft.com
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: mcr-microsoft-com
                stat_prefix: mcr-microsoft-com_passthr
        - filter_chain_match:
            server_names:
              - northeurope.data.mcr.microsoft.com
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: region-data-mcr-microsoft-com
                stat_prefix: region-data-mcr-microsoft-com_passthr
        - filter_chain_match:
            server_names:
              - guestnotificationservice.azure.com
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: guestnotificationservice-azure-com
                stat_prefix: guest-net_passthr
        {{- else }}
        filter_chains:
        - filters:
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              cluster: parent-passthrough
              stat_prefix: parent_https_passthr
        {{- end }}

      {{- if .Values.parent.enabled }}
      clusters:
      - name: management-azure-com
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: management-azure-com
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: management.azure.com
                    port_value: 443
      - name: login-windows-net
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: login-windows-net
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: login.windows.net
                    port_value: 443
      - name: www-google-com
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: www-google-com
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: google.com
                    port_value: 443
      - name: mcr-microsoft-com
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: mcr-microsoft-com
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: mcr.microsoft.com
                    port_value: 443
      - name: region-data-mcr-microsoft-com
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: region-data-mcr-microsoft-com
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: northeurope.data.mcr.microsoft.com
                    port_value: 443
      - name: guestnotificationservice-azure-com
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: guestnotificationservice-azure-com
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: guestnotificationservice.azure.com
                    port_value: 443
      #else if child layer point to parent proxy entry point
      {{- else }}
      clusters:
      - name: parent-passthrough
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: parent-passthrough
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .Values.parent.proxyIp }}
                    port_value: {{ .Values.parent.proxyHttpsPort }}
      {{- end }}