apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-configmap
data:
  envoy.yaml: |-
    admin:
      address:
        socket_address: { address: 0.0.0.0, port_value: 9901 }

    static_resources:
      listeners:
      - name: https_listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 50000

        listener_filters:
        - name: "single_tls_inspector"
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
        per_connection_buffer_limit_bytes: 32768  # 32 KiB
        filter_chains:
        - filter_chain_match:
            server_names:
              - management.azure.com
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: {{- if .Values.parent.enabled }} parent-passthrough  {{- else }} management-azure-com {{- end }}
                stat_prefix: mng-azure-com_passthr
        - filter_chain_match:
            server_names:
              - login.windows.net
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: {{- if .Values.parent.enabled }} parent-passthrough  {{- else }} login-windows-net {{- end }}
                stat_prefix: login-windows-net_passthr
        - filter_chain_match:
            server_names:
              - www.google.com
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: {{- if .Values.parent.enabled }} parent-passthrough  {{- else }} www-google-com {{- end }}
                stat_prefix: google-com_passthr
        - filter_chain_match:
            server_names:
              - mcr.microsoft.com
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: {{- if .Values.parent.enabled }} parent-passthrough  {{- else }} mcr-microsoft-com {{- end }}
                stat_prefix: mcr-microsoft-com_passthr
        - filter_chain_match:
            server_names:
              - northeurope.data.mcr.microsoft.com
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: {{- if .Values.parent.enabled }} parent-passthrough  {{- else }} region-data-mcr-microsoft-com {{- end }}
                stat_prefix: region-data-mcr-microsoft-com_passthr
        - filter_chain_match:
            server_names:
              - guestnotificationservice.azure.com
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                cluster: {{- if .Values.parent.enabled }} parent-passthrough  {{- else }} guestnotificationservice-azure-com {{- end }}
                stat_prefix: guest-net_passthr

      {{- if .Values.parent.enabled }}
      # If child layer point to parent proxy entrypoint
      clusters:
      - name: parent-passthrough
        type: LOGICAL_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: parent-passthrough
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .Values.parent.proxyIp }}
                    port_value: {{ .Values.parent.proxyHttpsPort }}
      
      {{- else }}
      # else if this is top layer point to outbound public URIs
      clusters:
      - name: management-azure-com
        type: LOGICAL_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: management-azure-com
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: management.azure.com
                    port_value: 443
      - name: login-windows-net
        type: LOGICAL_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: login-windows-net
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: login.windows.net
                    port_value: 443
      - name: www-google-com
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        load_assignment:
          cluster_name: www-google-com
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: www.google.com
                    port_value: 443
      - name: mcr-microsoft-com
        type: LOGICAL_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: mcr-microsoft-com
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: mcr.microsoft.com
                    port_value: 443
      - name: region-data-mcr-microsoft-com
        type: LOGICAL_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: region-data-mcr-microsoft-com
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: northeurope.data.mcr.microsoft.com
                    port_value: 443
      - name: guestnotificationservice-azure-com
        type: LOGICAL_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: guestnotificationservice-azure-com
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: guestnotificationservice.azure.com
                    port_value: 443
    {{- end }}
    
    layered_runtime:
      layers:
      - name: static_layer_0
        static_layer:
          overload:
            global_downstream_max_connections: 50000