apiVersion: v1
kind: Service
metadata:
  name: envoy-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: envoy-module
  ports:
    - protocol: TCP
      name: https
      port: {{ .Values.envoyReverseProxy.httpsPort }}
      targetPort: {{ .Values.envoyReverseProxy.httpsContainerPort }}
    - protocol: TCP
      name: obo
      port: {{ .Values.envoyReverseProxy.oboPort }}
      targetPort: {{ .Values.envoyReverseProxy.oboPort }}
