apiVersion: v1
kind: Service
metadata:
  name: envoy-https-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: envoy-module
  ports:
    - protocol: TCP
      port: {{ .Values.envoyReverseProxy.httsPort }}
      targetPort: {{ .Values.envoyReverseProxy.httpsContainerPort }}

