# System Squid proxy module/pod
apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-proxy-configmap
  labels:
    app: squid-proxy-module
data:
  squid.conf: |
    # TODO: Customize to your own setup and security requirements.
    {{- if .Values.parent }}
    cache_peer {{ .Values.parent.ipAddress }} parent {{ .Values.parent.port }} 0 no-query default login={{- .Values.parent.loginUser -}}:{{- .Values.parent.loginPassClear }}
    # cache_peer {{ .Values.parent.ipAddress }} parent {{ .Values.parent.port }} 0 no-query default login=PASSTHRU
    # never_direct allow all
    acl all src all
    auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwd
    auth_param basic realm proxy
    acl authenticated proxy_auth REQUIRED
    http_access allow authenticated
    {{- end }}

    {{- if not .Values.parent }}
    acl all src all
    # http_access allow all
    auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwd
    auth_param basic realm proxy
    acl authenticated proxy_auth REQUIRED
    http_access allow authenticated
    {{- end }}

    # Default config.
    acl SSL_ports port 443
    acl Safe_ports port 80
    acl Safe_ports port 21
    acl Safe_ports port 443
    acl Safe_ports port 70
    acl Safe_ports port 210
    acl Safe_ports port 1025-65535
    acl Safe_ports port 280
    acl Safe_ports port 488
    acl Safe_ports port 591
    acl Safe_ports port 777
    acl CONNECT method CONNECT
    http_access deny !Safe_ports
    http_access deny CONNECT !SSL_ports
    http_access allow localhost manager
    http_access deny manager
    http_access allow localhost
    http_access deny all
    http_port {{ .Values.squidProxy.port }}
    coredump_dir /var/spool/squid
    refresh_pattern ^ftp:           1440    20%     10080
    refresh_pattern ^gopher:        1440    0%      1440
    refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
    refresh_pattern .               0       20%     4320

  htpasswd: |
    {{ .Values.htpasswd }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-proxy-module-deployment
  labels:
    app: squid-proxy-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid-proxy-module
  template:
    metadata:
      labels:
        app: squid-proxy-module
    spec:
      volumes:
        - name: squid-proxy-volume
          configMap:
            name: squid-proxy-configmap
            items:
            - key: squid.conf
              path: squid.conf
            - key: htpasswd
              path: passwd
      containers:
      - name: squid-proxy-module
        image: {{ .Values.squidProxy.image }}
        imagePullPolicy: Always
        volumeMounts:
        - name: squid-proxy-volume
          mountPath: /etc/squid/
        ports:
        - containerPort: {{ .Values.squidProxy.port }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: squid-proxy-module
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: squid-proxy-module
  ports:
    - protocol: TCP
      port: {{ .Values.squidProxy.port }}
      targetPort: {{ .Values.squidProxy.port }}