apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: iot-edge-scada-release
  namespace: edge-app1
spec:
  interval: 1m
  chart:
    spec:
      chart: iot-edge-scada
      sourceRef:
        kind: HelmRepository        
        name: iot-edge-accelerator-repo
        namespace: edge-app1
      interval: 1m
