# TODO: Add overarching component configuration.
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-pub-sub
  namespace: edge-app
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master.edge-core.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password
  # Lock down type of access for each service.
  - name: publishingScopes
    value: "simulated-temperature-sensor-module=telemetry;data-gateway-module=;opc-publisher-module=telemetry"
  - name: subscriptionScopes
    value: "simulated-temperature-sensor-module=;data-gateway-module=telemetry;opc-publisher-module="
  # Lock down the topics on this pubsub component.
  - name: allowedTopics
    value: "telemetry"

 # uncomment below for connecting to redis cache instances over TLS (ex - Azure Redis Cache)
  # - name: enableTLS
  #   value: true 
scopes:
- data-gateway-module
- simulated-temperature-sensor-module
- opc-publisher-module