name: Main - Release Helm Charts - Envoy
on: 
  push:
    branches: 
      - main
    paths:
      # Only run this when chart file is updated.
      - 'deployment/helm/envoy/Chart.yaml'
      
jobs:
  Release-Artifacts:      
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Setup Helm
      uses: azure/setup-helm@v3.5 
      with:
        version: v3.9.2
    
    - name: Add Helm dependencies
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.1.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        charts_dir: deployment/helm
